### ISSUE TITLE
Client side ClassLoader issue if query involves multiple providers

### ISSUE THREAD

**Issue by alexanderdean** [Cascading/lingual#15]
There is a ClassLoader issue, that only occurs when you have different providers with their own jars as source and sink.

For full details on this:

https://groups.google.com/forum/#!topic/lingual-user/V-Sk1KKsPD0

As a temporary workaround (assuming you are using Lingual shell):

```
$ lingual catalog --provider --add cascading:cascading-jdbc-mysql:2.5.1:provider
$ lingual catalog --provider --add cascading:cascading-hbase:2.2.0:provider
# or whatever providers you are loading...

$ find /home/$USER/.ivy2/cache/cascading -type f -iname "cascading*jar" -exec cp '{}' $(dirname `which lingual`) ';'
```

**Comment by joeposner** [comment]
This is fixed in the current wip as referenced above. Closing as resolved.

**Comment by alexanderdean** [comment]
Thanks for the speedy fix!
