### ISSUE TITLE
Update Lingual-HBase tutorial to use log files without headers...

### ISSUE THREAD

**Issue by alexanderdean** [Cascading/lingual#26]
... and in the tutorial, make a note of explicitly configuring the stereotype without headers.

This will save so much pain, given how rare it is on Hadoop to use files with headers...

**Comment by fs111** [comment]
good idea. Can you open the issue over here https://github.com/Cascading/tutorials ? Thanks!

**Comment by alexanderdean** [comment]
Done, closing this one. https://github.com/Cascading/tutorials/issues/3
