### ISSUE TITLE
Time part of timestamp fields are parsed as 00:00:00

### ISSUE THREAD

**Issue by bspaans** [Cascading/lingual#27]
I'm experiencing a curious problem on Lingual 1.1.0. Everything is working as expected, but when trying to parse a timestamp field like "2014-01-01 01:02:03" the data comes out like this: "2014-01-01 00:00:00"

Test case:

```
lingual catalog --init
lingual catalog --schema timestampTest --add
lingual catalog --schema timestampTest --stereotype times --add --columns ts --types timestamp
lingual catalog --schema timestampTest --table times --stereotype times --add data.csv

echo -e "ts\n\"2014-01-01 01:02:03\"" > data.csv

echo -e "select * from \"timestampTest\".\"times\";\n!quit\n" | lingual shell
```

Outputs:

```
+------------------------+
|           ts           |
+------------------------+
| 2014-01-01 00:00:00.0  |
+------------------------+
```

One workaround I have found is to add the table before the stereotype:

```
lingual catalog --init
lingual catalog --schema timestampTest --add
lingual catalog --schema timestampTest --table times --stereotype times --add data.csv
lingual catalog --schema timestampTest --stereotype times --add --columns ts --types timestamp

echo -e "ts\n\"2014-01-01 01:02:03\"" > data.csv

echo -e "select * from \"timestampTest\".\"times\";\n!quit\n" | lingual shell
```

Which outputs the expected:

```
+----------------------+
|          ts          |
+----------------------+
| 2014-01-01 01:02:03  |
+----------------------+
```

But this also adds a stereotype named "data" in the catalog which doesn't seem right. 

The documentation suggests that the stereotype should be added before the table, but maybe I'm missing something there?

**Comment by fs111** [comment]
Hi Bart,

thanks for the bug report and the test case. This is indeed a problem. We are going to investigate the problem.

**Comment by joeposner** [comment]
The fix to preserve precisions is live in the current wip-1.1 release.

**Comment by bspaans** [comment]
Thank you very much!
