### ISSUE TITLE
Feature Request: Allow setting of app name for lingual shell

### ISSUE THREAD

**Issue by sporkthrower** [Cascading/lingual#31]
Currently the app name defaults to `lingual-hadoop`.  

Particularly when trying to observe lingual shell executions in Driven, it would be helpful for the user to be able to set this.

**Comment by fs111** [comment]
You can overwrite settings via LINGUAL_CONFIG or by putting them in the config file in the catalog directory. If you set "cascading.app.name" to the value you want, it should do the trick: http://docs.cascading.org/lingual/1.1/#_setting_job_properties

**Comment by sporkthrower** [comment]
Thanks, pointing @rdesmond here as he was looking to be able to do this.   That seems sufficient to me, so closing request as well

**Comment by rdesmond** [comment]
@sporkthrower @fs111 this is perfect. thanks!
